### ISSUE TITLE
构建后，搜狗浏览器会出现不兼容。

### ISSUE THREAD

**Issue by ghost** [antfu/vitesse-nuxt#107]
### Describe the bug

Uncaught SyntaxError: Unexpected token '='    asyncData.js?v=68f4cccb:29

如果使用 vite/legacy-polyfills 可以解决该问题，请问还有跟好的方法吗？

### Reproduction

无

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 21.32 GB / 31.75 GB
  Binaries:
    Node: 18.18.2 - D:\tool\nvm\nodejs\node.EXE
    Yarn: 1.22.19 - D:\tool\nvm\node_global\yarn.CMD
    npm: 9.8.1 - D:\tool\nvm\nodejs\npm.CMD
    pnpm: 8.12.0 - D:\tool\nvm\node_global\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [ ] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
The issue tracker is not for asking questions. Please do your research.
